### 非流式调用
GET http://localhost:8081/api-template/ai/bailian/agent/call?message=国家奖学金评选有什么条件?
Accept: application/json

### 流式调用
GET http://localhost:8081/api-template/ai/bailian/agent/stream?message=你好，请问你的知识库文档主要是关于什么内容的?
Accept: text/event-stream